"""add_indexes

Revision ID: c09261d2fbd5
Revises: 
Create Date: 2026-03-08 11:43:31.875997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09261d2fbd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_responses', schema=None) as batch_op:
        batch_op.create_index('ix_vr_message_id', ['email_message_id'], unique=False)
        batch_op.create_index('ix_vr_rfq_id', ['rfq_id'], unique=False)
        batch_op.create_index('ix_vr_rfq_vendor', ['rfq_id', 'vendor_email'], unique=False)

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index('ix_vendors_rfq_id', ['rfq_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index('ix_vendors_rfq_id')

    with op.batch_alter_table('vendor_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_vr_rfq_vendor')
        batch_op.drop_index('ix_vr_rfq_id')
        batch_op.drop_index('ix_vr_message_id')

    # ### end Alembic commands ###
